
export const LEADERBOARD_CONTRACT =
"CCYXFZ6HBPRMQQSKIYJCAOHFJRWT4EUWBYDIWMD6PFEQ5ECZA4YQE7C4";

export const TASK_CONTRACT =
"CCHVBJX72GNRE2WPML4GNOOEOS737AEHI66AKCBZRPXCQCJWWVD2NQFB";

export const TOKEN_CONTRACT =
"CCHD4EXBCDTIK6XPM7UJTLPKHKKFEEYEF2757XPUZLEYDWUVBKGWA5GM";

export const RPC_URL = "https://soroban-testnet.stellar.org";